export { default as primary } from './primary';
export { default as blue } from './blue';
export { default as red } from './red';
export { default as green } from './green';
export { default as grey } from './grey';
export { default as orange } from './orange';
export { default as purple } from './purple';
export { default as teal } from './teal';
export { default as yellow } from './yellow';
